### ISSUE TITLE
Can we add confidence intervals to sensitivity etc?

### ISSUE THREAD

**Issue by woook** [moka-guys/benchmarking_tool#4]
here's R code for sensitivity CI's:

```
install.packages("epiR")
library("epiR")

#Provide numbers in order TP,FP,FN,TN   
dat <- as.table(matrix(c(11068,36,105,14141122), nrow = 2, byrow = TRUE))
rval <- epi.tests(dat, conf.level = 0.95)
print(rval); summary(rval)
```

Just realised that this package needs TN though, which we don't have...

**Comment by andyb3** [comment]
Already an issue for this here: https://github.com/moka-guys/dnanexus_happy/issues/4

**Comment by andyb3** [comment]
DNAnexus app is being updated to output confidence intervals. Will need to add this information to the summary in the email sent to user.
